[package]
name = "bpf-map"
version = "0.1.0"
authors = ["Jan-Erik Rediger <janerik@fnordig.de>"]

build = "build.rs"

[dependencies]
clap = "2.20.5"
error-chain = "0.10.0"

[build-dependencies]
gcc = "0.3"
